POST {{baseUrl}}/login HTTP/1.1
Content-Type: application/json

{
    "eMail": "mert@project.com",
    "password": "password"
}

###

DELETE {{baseUrl}}/my-account HTTP/1.1
Content-Type: application/json
token: {{token}}

{
    "password": "password"
}

###

PUT {{baseUrl}}/my-account HTTP/1.1
Content-Type: application/json
token: {{token}}

{
    "name": "mert",
    "surname": "bereket",
    "eMail": "mert@project.com",
    "password": "password",
    "userName": "MertBereket"
}

###

PUT {{baseUrl}}/change-password HTTP/1.1
Content-Type: application/json
token: {{token}}

{
    "password": "password",
    "NewPassword": "password"
}

###

POST {{baseUrl}}/password-control HTTP/1.1
Content-Type: application/json
token: {{token}}

{
    "password": "password"
}

###

GET {{baseUrl}}/token-decode HTTP/1.1
Content-Type: application/json
token: {{token}}
