GET {{baseUrl}}/masalar HTTP/1.1
Content-Type: application/json
token: {{token}}

###


GET {{baseUrl}}/masalar/1 HTTP/1.1
Content-Type: application/json
token: {{token}}

###

POST {{baseUrl}}/masalar HTTP/1.1
Content-Type: application/json
token: {{token}}

{
    "Ad": "Bahçe",
    "tableNo": 12
}

###

DELETE {{baseUrl}}/masalar HTTP/1.1
Content-Type: application/json
token: {{token}}

{
    "ID" : 5
}


###

DELETE {{baseUrl}}/masalar/delete/27 HTTP/1.1
Content-Type: application/json
token: {{token}}


###


PUT {{baseUrl}}/masalar HTTP/1.1
Content-Type: application/json
token: {{token}}

{
    "ID": 18,
    "Ad": "Bahçe",
    "tableNo": 876
}