GET {{baseUrl}}/menu HTTP/1.1
Content-Type: application/json
token: {{token}}

###


GET {{baseUrl}}/menu/1 HTTP/1.1
Content-Type: application/json
token: {{token}}

###

POST {{baseUrl}}/menu HTTP/1.1
Content-Type: application/json
token: {{token}}

{
    "Ad": "Americano",
    "Kategori": 2,
    "Fiyat": 10
}

###

DELETE {{baseUrl}}/menu HTTP/1.1
Content-Type: application/json
token: {{token}}

{
    "ID" : 4
}

###

PUT {{baseUrl}}/menu HTTP/1.1
Content-Type: application/json
token: {{token}}

{
    "ID": 4,
    "Ad": "İçeceklerimiz",
    "Kategori": 2,
    "Fiyat": 9
}