GET {{baseUrl}}/user HTTP/1.1
Content-Type: application/json
token: {{token}}

###

GET {{baseUrl}}/user/1 HTTP/1.1
Content-Type: application/json
token: {{token}}

###

POST {{baseUrl}}/user HTTP/1.1
Content-Type: application/json
token: {{token}}

{
    "userName": "AhmetCetiner",
    "name": "Ahmet",
    "surname": "Çetiner",
    "eMail": "ahmet@project.com",
    "password": "password",
    "UserTypeName": "Administrator"
}

###

PUT {{baseUrl}}/user HTTP/1.1
Content-Type: application/json
token: {{token}}

{
    "userName": "MertBereket",
    "ID": 1,
    "name": "Mert",
    "surname": "Bereket",
    "eMail": "mert@project.com",
    "password": "password",
    "UserTypeName": "Root"
}

###

DELETE  {{baseUrl}}/user HTTP/1.1
Content-Type: application/json
token: {{token}}

{
    "Id": 4
}